[build]
  command = "npm run build"
  publish = "out"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "frame-ancestors 'self'"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
